### PR TITLE
fix: `serializeNetworkSecurityMap` not mapping to null

### LINKED ISSUE #211: iOS - Connect function crashes the app
iOS - 15.2
-- 
wifi_iot: ^0.3.10
--

When calling WifiForIoTPlugin.connect the app crashes to null error. 

Only mandatory argument should be 'ssid', but when not providing "password" or "security" arguments the app crashes to "Could not cast value of type 'NSNull' (0x1dae296c0) to 'NSString' (0x1dae28b18).". 

When debugging with xcode those values comes to connect function as nil. Then when  plugin trying access  them in SwiftWifiIotPlugin  class in lines 126-128 if the value is nil the app crashes.

### PR DESCRIPTION
**Pull request by daadu**
Closes #211

### CODE REVIEW

**Comment by daadu** [comment]
Review please - @diegotori @mavyfaby @felixsmart @Hallot @nikolip

**Comment by daadu** [comment]
Can be tested with:

```yaml
  wifi_iot: #^0.3.0
    git:
      url: https://github.com/daadu/WiFiFlutter
      path: packages/wifi_iot
      ref: fix-211
```

**Comment by daadu** [comment]
This is a bit urgent - so will merge it if no response by tomorrow.

**Comment by diegotori** [comment]
LGTM.

**Comment by daadu** [comment]
Fix released on pub with [v0.3.12](https://pub.dev/packages/wifi_iot/versions/0.3.12).

**Comment by nikolip** [comment]
Hey!

Sorry for not responding earlier.
When looking the pr - it seems like you have fixed the problem only when not providing security argument. (That works now)
But there is still the issue when you try to join an open wifi (no password needed).
eg. 

`
WiFiForIoTPlugin.connect("wifi-ssid");
`

App still crashes then on SwiWifiIotPlugin.swift line 126 when accessing call aguments.
`
 let sPassword = (call.arguments as? [String : AnyObject])?["password"] as! String?
`

**Pull request merged**
