### PR TITLE
Major Android Revamp [Wifi Only]

### PR DESCRIPTION
**Pull request by daadu**
Picking up with changes in Flutter (Android side) and Android SDK

# TODO
- [x] migrate to Android v2 Embedding [[doc](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration)]
- [x] migrate to `androidx` dependencies (example app) [[docs](https://flutter.dev/docs/development/androidx-migration)]
- [x] upgrade default compile SDK (29 0r 30) and gradle version (latest) (plugin and example app)
- [x] handle deprecated methods in Android SDK >= 29 [[ref](https://github.com/alternadom/WiFiFlutter/issues/80#issuecomment-677429505)]
  - [x] Wifi methods changed
    - [x] `loadWifiList(poResult);`
      - `WifiManager.startScan` [deprecated in API 28] will not be supported in future, Lint is not giving warnings though. 
      -  Use cached result via `WifiManger.getScanResult`
    - [x] `setEnabled(poCall, poResult);`
      - `WifiManager.setWifiEnabled` [deprecated in API 29] it will always fails
      - Add warning in the docs for the usage
    - [x] `connect(poCall, poResult);`
       - `connectTo` method called in `connect` uses a lot of deprecated classes and methods
       - rename old `connectTo` to `connectToDeprecated` and add new implementation in `connectTo`
       - add warning in readme as WEP is not supported
    - [x] `findAndConnect(poCall, poResult);`
      - same as `connect`
    - [x] `isConnected(poResult);`
      - remove `NetworkInfo` from import
      - `ConnectionManager.getNetworkInfo` [deprecated in API 23], Lint is not giving warnings though.
      - rename old `isConnected` to `isConnectedDeprecated` and add new implementation    
    - [x] `disconnect(poResult);`
      - `WifiManger.disconnect` [deprecated in API 29]
      - use `ConnectivityManager.unregisterCallback` to disconnect for API >= 29
    - [x] `removeWifiNetwork(poCall, poResult);`
      - `WifiManager.getConfiguredNetworks` [deprecated in API 29], `WifiManager.removeNetwork` [deprecated in API 29], `WifiConfiguration` [deprecated in API 29]
      - add error for API >= 29
      - add warning to readme
    - [x] `isRegisteredWifiNetwork(poCall, poResult);`
      - `WifiManager.getConfiguredNetworks` [deprecated in API 29], `WifiManager.removeNetwork` [deprecated in API 29], `WifiConfiguration` [deprecated in API 29]
      - add error for API >= 29
      - add warning to readme
  - ~~Access Point methods~~
    - ~~`getWiFiAPSSID(poResult);`~~
      - `WifiConfiguration` [deprecated in API 29]
    - ~~`setWiFiAPSSID(poCall, poResult);`~~
      - `WifiConfiguration` [deprecated in API 29]
    - ~~`isSSIDHidden(poResult);`~~
      - `WifiConfiguration` [deprecated in API 29]
    - ~~`setSSIDHidden(poCall, poResult);`~~
      - `WifiConfiguration` [deprecated in API 29]
    - ~~`getWiFiAPPreSharedKey(poResult);`~~
      - `WifiConfiguration` [deprecated in API 29]
    - ~~`setWiFiAPPreSharedKey(poCall, poResult);`~~
      - `WifiConfiguration` [deprecated in API 29]
- [x] other changes/refactor
  - [x] remove unused `sudoForResult` and related methods.
  - [x] replaces `android.permission.ACCESS_COARSE_LOCATION` with `android.permission.ACCESS_FINE_LOCATION`, since the documentation suggest it now.
- ~~resolve deprecation warning while `flutter build apk`~~

## Note for tester/reviewers

All the changes should be backward compatible, ie. should work with all flutter app as it is by just upgrading the package version. There for I encourage the reviewer to test both scenarios (>=29 and < 29; embedding v1 and v2).

To test this branch use the following in dependencies in puspec.yaml of your app:
```yaml
dependencies:
  wifi_iot:
    git: 
      url: https://github.com/daadu/WiFiFlutter.git
      ref: android-major-revamp
```

This PR should potentially resolve following issues:
- #60
- #80
- #85

### CODE REVIEW

**Comment by Niek** [comment]
Great work @daadu! I tested your branch and it works fine, no errors or issues in the functions that we use: ``loadWifiList()`` and `connect()`/`disconnect()`.

**Comment by daadu** [comment]
> Great work @daadu! I tested your branch and it works fine, no errors or issues in the functions that we use: `loadWifiList()` and `connect()`/`disconnect()`.
did you test with both sets: Android SDK >=29 and < 29; Android Embedding v1 and v2?
> 
> BTW there's a new official plugin that offers some "info" functions: https://github.com/flutter/plugins/tree/master/packages/wifi_info_flutter/wifi_info_flutter
Will think of add this once the mammoth is dealt with!

**Comment by daadu** [comment]
@alternadom `sudoForResult`, `readFully`, `Closer` methods/classes where unused, I have removed. Are they of any use?

**Comment by daadu** [comment]
Seems like Access Point methods are complicated using "mirrors" (hidden API) and there has been no issue raised for AP, hence this PR will not cover it.

There for #83 is out of scope of this PR.

**Comment by daadu** [comment]
@Niek @krishnaaro Please test and review this.

**Comment by daadu** [comment]
unlinking #78 since AP is out of scope of this PR

**Comment by daadu** [comment]
@alternadom This PR LGTM.

Just to be safe can we release this as "alpa" on pub.dev, and then maybe after few weeks push to main version. I was thinking something like `1.1.2-alpha.0` for now.

**Comment by daadu** [comment]
Although I found it later, this [article/post](https://www.droidcon.com/news-detail?content-id=/repository/collaboration/Groups/spaces/droidcon_hq/Documents/public/news/android-news/Connecting%20to%20Wi-Fi%20devices%20with%20RxJava%20in%20Android) is a good resource that explains and clarifies the new APIs.

**Comment by Niek** [comment]
Thanks for the amazing work @daadu! Is this ready for merging yet?

**Comment by daadu** [comment]
> Thanks for the amazing work @daadu! Is this ready for merging yet?

Your welcome @Niek. It LGTM for merging, as mentioned before, would like if this changes are released as "alpha" (something like `v1.1.2-alpha.0`) before proper release with  `v1.1.2`

**Comment by Niek** [comment]
Great, I do see one exception when changing target SDK to 30, but not sure if it's coming from this plugin:
```java
W/ConnectionTracker(21779): Exception thrown while unbinding
W/ConnectionTracker(21779): java.lang.IllegalArgumentException: Service not registered: lp@3865763
W/ConnectionTracker(21779):     at android.app.LoadedApk.forgetServiceDispatcher(Unknown Source:195)
W/ConnectionTracker(21779):     at android.app.ContextImpl.unbindService(Unknown Source:11)
W/ConnectionTracker(21779):     at android.content.ContextWrapper.unbindService(Unknown Source:2)
W/ConnectionTracker(21779):     at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):1)
W/ConnectionTracker(21779):     at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):2)
W/ConnectionTracker(21779):     at lq.D(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):10)
W/ConnectionTracker(21779):     at lc.a(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):2)
W/ConnectionTracker(21779):     at ee.run(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):3)
W/ConnectionTracker(21779):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(21779):     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(21779):     at ix.run(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):6)
```

**Comment by daadu** [comment]
@Niek Android SDK 30 (https://github.com/flutter/engine/pull/20479) is not still supported by flutter engine in stable channel. Although it has been merged with master, so could be available `master` or `dev`.

Try with 29 and/or change the flutter channel and test with  30.

**Comment by daadu** [comment]
@Niek Also did the functionality worked (irrespect of the logs)?

**Comment by daadu** [comment]
@Niek Also the error looks like firebase plugin issue [https://github.com/firebase/firebase-android-sdk/issues/1662]

**Comment by daadu** [comment]
@Niek Looks like firebase is not ready for v30!!

**Comment by daadu** [comment]
#85 reported issue with internet connectivity after connecting to wifi.

**Pull request merged**
