### PR TITLE
feat(ios): getIP implemented

### PR DESCRIPTION
**Pull request by DominikStarke**
This uses the same approach as network_info_plus:

https://github.com/fluttercommunity/plus_plugins/blob/a1b18402790b65f4f23cbb5d6ed7bb248480a70e/packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfoPlusPlugin.m#L54

The functionality is split across 2 functions, so we could as well implement getIPv6 by calling getNetworkInterface with AF_INET6 instead of AF_INET

### CODE REVIEW

**Comment by daadu** [comment]
@DominikStarke I had created an issue related it #149.

Can we also implement `getCurrentSignalStrength` - the info in iOS is not same as android which give RSSI. There we need to transform the iOS result to RSSI to have parity with android.

**Comment by daadu** [comment]
Also need to make necessary changes in README.

**Comment by DominikStarke** [comment]
> Can we also implement getCurrentSignalStrength

Unfortunately not. There is no API to directly access signal strength on iOS.
NEHotspotNetwork only holds a value for signalStrength, if discovered by a NEHotspotHelper registrar, which only works if:
1) The app has the "Network Extensions" capability
2) The user simultaniously has the iOS WiFi settings app opened
3) The app may run in the background

**Review by daadu — APPROVED** [review]

**Comment by daadu** [comment]
This feature has landed on pub.dev with v0.3.8.

**Pull request merged**
