### PR TITLE
refactor(ios): handle deprecation of `CNCopyCurrentNetworkInfo `

### LINKED ISSUE #142: ⚠ [ios] handle deprecation of CNCopyCurrentNetworkInfo
- `getSSID`, `getBSSID` for ios - should fail because of it
- `getSSID` is internally used in handling  `isEnabled`, `connect`, `disconnect`, those might be affected as well

# Docs
- CNCopyCurrentNetworkInfo - https://developer.apple.com/reference/systemconfiguration/1614126-cncopycurrentnetworkinfo

### PR DESCRIPTION
**Pull request by daadu**
Using `NEHotspotNetwork.fetchCurrent` instead

Closes #142 #105 #75 #121

### CODE REVIEW

**Comment by Niek** [comment]
Awesome, I can't test right now but this is great work.

**Comment by diegotori** [comment]
LGTM. Hopefully, we'll see a new release shortly thereafter.

**Comment by phan-dev** [comment]
@daadu I got this message on both iOS real device and simulator

`[] NEHotspotNetwork nehelper sent invalid result code [1] for Wi-Fi information request`

**Comment by daadu** [comment]
> @daadu I got this message on both iOS real device and simulator
> 
> `[] NEHotspotNetwork nehelper sent invalid result code [1] for Wi-Fi information request`

@phan-dev Just confirming - did you add "Network Extension" to the iOS proj?

**Comment by phan-dev** [comment]
image

@daadu tested on real device - iOS 14.4.2 and simulator - iOS 14.5

**Comment by daadu** [comment]
I don't have iOS 14 devices, have not tested it personally.

Will test it myself in some days

**Comment by diegotori** [comment]
@phan-dev In addition to the info of this [link](https://stackoverflow.com/a/64852900), You need to make sure that your App ID has the following capabilities enabled:

* `Access WiFi Information`
* `Hotspot`
* `Network Extensions`
* `Wireless Accessory Configuration`

Also, ensure that your entitlements file contains the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.networking.HotspotConfiguration</key>
	<true/>
	<key>com.apple.developer.networking.networkextension</key>
	<array>
		<string>app-proxy-provider</string>
	</array>
	<key>com.apple.developer.networking.wifi-info</key>
	<true/>
	<key>com.apple.external-accessory.wireless-configuration</key>
	<true/>
</dict>
</plist>
```

**Comment by diegotori** [comment]
@phan-dev also, this Apple Dev Forum [post](https://developer.apple.com/forums/thread/670970) has a working example of the bare minimum needed to connect to a WiFi Network for iOS 14 and higher along with the necessary entitlements to use and the plist entries to make.

**Comment by diegotori** [comment]
@daadu any updates?

**Comment by daadu** [comment]
This has landed on pub.dev with v0.3.4.

**Comment by daadu** [comment]
@diegotori Took long because was not sure if it was tested well.

**Pull request merged**
