### PR TITLE
migrate to android embedding v2 with backward compatibility

### PR DESCRIPTION
**Pull request by daadu**
- [WifiIotPlugin] removed private constructor and replaces with `initWithContext` and `initWithActivity` method; added `cleanup` method
- [WifiIotPlugin] added `FlutterPlugin` and `ActivityAware` interfaces and override associated methods

Guide followed: https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

### CODE REVIEW

**Comment by daadu** [comment]
I would encourage reviewers to test example app with both v1 and v2 embedding (by changing `AndroidManifest.xml` and `MainActivity.java` of example flutter app)

**Comment by daadu** [comment]
The plugin should work in "background" (without activity) without any issue, if the appropriate permissions are given (for which activity is required).

Should we add this in README somewhere?

**Comment by daadu** [comment]
@alternadom That was quick from you!! Did you test it by running it?

**Comment by alternadom** [comment]
Sorry, we are not using currently the WiFiFlutter library.. so I was expecting you were sure about it :)

**Comment by daadu** [comment]
I have tested it but want someone else to confirm it, since there are lot of permutations and combinations.

**Pull request merged**
