### PR TITLE
fix: proper serializing to avoid issue when obfuscated

### LINKED ISSUE #185: android connect release mode with obfuscate not working
This is an Android only issue.

findAndConnect works in debug and release mode:

    WiFiForIoTPlugin.findAndConnect(network_ssid,
               password: password)

connect works only in debug mode:

    WiFiForIoTPlugin.connect(network_ssid,
               security: NetworkSecurity.WPA,
               password: password)

I build a release using:

    flutter build -v apk --split-per-abi --obfuscate --split-debug-info=build/app/outputs/symbols

I've compared findAndConnect and connect in WifiIotPlugin.java, the main difference being that the security type is extracted from the wifi scan result, rather than in the case of "connect" being passed as a parameter.

Looking at connect in wifi_iot.dart the security parameter is converted to a string:

    "security": security.toString().substring('$NetworkSecurity'.length + 1)

NetworkSecurity is an enum, obfuscation will scrabble the enum's strings, so the security.toString() will not return "WPA" as expected on android with obfuscation.

My app handles this kind of situation, using a mapping from enum values to strings, as so:

    enum MainContent {
      home,
      menu,
    }

    Map<MainContent, String> breadcrumbTitles = {
      MainContent.home: "Home",
      MainContent.menu: "Menu",
    };

    Queue breadcrumbs = Queue<MainContent>();
    String showTitle = "";

    if (breadcrumbs.isNotEmpty) {
      selectedContent = breadcrumbs.last;
      showTitle = breadcrumbTitles[selectedContent];
    }

Hope that helps, both to fix and other who may have experienced the same.

https://github.com/flutter/flutter/issues/58090

### PR DESCRIPTION
**Pull request by daadu**
Closes #185

### CODE REVIEW

**Comment by daadu** [comment]
Review please - @diegotori @mavyfaby @FelixSmart @nathan2day @Hallot

**Comment by daadu** [comment]
Cloud be tested with:

```yaml
  wifi_iot: #^0.3.0
    git:
      url: https://github.com/alternadom/WiFiFlutter
      path: packages/wifi_iot
      ref: fix-not-working-with-obfuscate
```

**Review by Hallot — APPROVED** [review]

**Comment by diegotori** [comment]
LGTM. As long as the platform channel validates the incoming input from Flutter-land, which I'm sure it's probably already happening.

**Comment by daadu** [comment]
Released with [v0.3.11](https://pub.dev/packages/wifi_iot/versions/0.3.11).

**Pull request merged**
